//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	// Mixin content Type 1126 with alias "baseContent"
	/// <summary>_Base Content</summary>
	public partial interface IBaseContent : IPublishedContent
	{
		/// <summary>Main Content</summary>
		IHtmlString MainContent { get; }

		/// <summary>Main Content Table Colour</summary>
		object MainContentTableColour { get; }

		/// <summary>Section Navigation Title</summary>
		string SectionNavigationTitle { get; }
	}

	/// <summary>_Base Content</summary>
	[PublishedContentModel("baseContent")]
	public partial class BaseContent : PublishedContentModel, IBaseContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main Content
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return GetMainContent(this); }
		}

		/// <summary>Static getter for Main Content</summary>
		public static IHtmlString GetMainContent(IBaseContent that) { return that.GetPropertyValue<IHtmlString>("mainContent"); }

		///<summary>
		/// Main Content Table Colour
		///</summary>
		[ImplementPropertyType("mainContentTableColour")]
		public object MainContentTableColour
		{
			get { return GetMainContentTableColour(this); }
		}

		/// <summary>Static getter for Main Content Table Colour</summary>
		public static object GetMainContentTableColour(IBaseContent that) { return that.GetPropertyValue("mainContentTableColour"); }

		///<summary>
		/// Section Navigation Title: Enter label for contextual navigation page bar. Leave empty to remove navigation point.
		///</summary>
		[ImplementPropertyType("sectionNavigationTitle")]
		public string SectionNavigationTitle
		{
			get { return GetSectionNavigationTitle(this); }
		}

		/// <summary>Static getter for Section Navigation Title</summary>
		public static string GetSectionNavigationTitle(IBaseContent that) { return that.GetPropertyValue<string>("sectionNavigationTitle"); }
	}
}
