//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	// Mixin content Type 1125 with alias "baseArticleGrid"
	/// <summary>_Base Article Grid</summary>
	public partial interface IBaseArticleGrid : IPublishedContent
	{
		/// <summary>Main Content Placeholder</summary>
		Newtonsoft.Json.Linq.JToken MainContentPlaceholder { get; }
	}

	/// <summary>_Base Article Grid</summary>
	[PublishedContentModel("baseArticleGrid")]
	public partial class BaseArticleGrid : PublishedContentModel, IBaseArticleGrid
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseArticleGrid";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseArticleGrid(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseArticleGrid, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main Content Placeholder
		///</summary>
		[ImplementPropertyType("mainContentPlaceholder")]
		public Newtonsoft.Json.Linq.JToken MainContentPlaceholder
		{
			get { return GetMainContentPlaceholder(this); }
		}

		/// <summary>Static getter for Main Content Placeholder</summary>
		public static Newtonsoft.Json.Linq.JToken GetMainContentPlaceholder(IBaseArticleGrid that) { return that.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("mainContentPlaceholder"); }
	}
}
