//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Data] Search Filter</summary>
	[PublishedContentModel("dataSearchFilter")]
	public partial class DataSearchFilter : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataSearchFilter";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataSearchFilter(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataSearchFilter, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Filter Title
		///</summary>
		[ImplementPropertyType("filterTitle")]
		public string FilterTitle
		{
			get { return this.GetPropertyValue<string>("filterTitle"); }
		}

		///<summary>
		/// Taxonomies
		///</summary>
		[ImplementPropertyType("taxonomies")]
		public IEnumerable<IPublishedContent> Taxonomies
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("taxonomies"); }
		}
	}
}
