//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>Profile Item</summary>
	[PublishedContentModel("dataProfileItem")]
	public partial class DataProfileItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataProfileItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataProfileItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataProfileItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("itemImage")]
		public IPublishedContent ItemImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("itemImage"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("itemName")]
		public string ItemName
		{
			get { return this.GetPropertyValue<string>("itemName"); }
		}

		///<summary>
		/// Item Profile
		///</summary>
		[ImplementPropertyType("itemProfile")]
		public string ItemProfile
		{
			get { return this.GetPropertyValue<string>("itemProfile"); }
		}

		///<summary>
		/// Role/Subtitle
		///</summary>
		[ImplementPropertyType("itemRoleSubtitle")]
		public string ItemRoleSubtitle
		{
			get { return this.GetPropertyValue<string>("itemRoleSubtitle"); }
		}
	}
}
