//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>File Extension</summary>
	[PublishedContentModel("fileExtension")]
	public partial class FileExtension : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fileExtension";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FileExtension(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FileExtension, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// File extensions: List of file extensions for this file type
		///</summary>
		[ImplementPropertyType("fileExtensions")]
		public IEnumerable<string> FileExtensions
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("fileExtensions"); }
		}

		///<summary>
		/// File type: Descriptive text for this file type
		///</summary>
		[ImplementPropertyType("fileType")]
		public string FileType
		{
			get { return this.GetPropertyValue<string>("fileType"); }
		}
	}
}
