//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Form] Application Form Step Eleven</summary>
	[PublishedContentModel("formStepEleven")]
	public partial class FormStepEleven : PublishedContentModel, IBaseHeading, IBaseMetaInformation, IBaseNavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "formStepEleven";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FormStepEleven(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FormStepEleven, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Adult Learning First Choice Label
		///</summary>
		[ImplementPropertyType("labelAdultLearningFirstChoice")]
		public string LabelAdultLearningFirstChoice
		{
			get { return this.GetPropertyValue<string>("labelAdultLearningFirstChoice"); }
		}

		///<summary>
		/// Adult Learning Second Choice Label
		///</summary>
		[ImplementPropertyType("labelAdultLearningSecondChoice")]
		public string LabelAdultLearningSecondChoice
		{
			get { return this.GetPropertyValue<string>("labelAdultLearningSecondChoice"); }
		}

		///<summary>
		/// Adult Learning Third Choice Label
		///</summary>
		[ImplementPropertyType("labelAdultLearningThirdChoice")]
		public string LabelAdultLearningThirdChoice
		{
			get { return this.GetPropertyValue<string>("labelAdultLearningThirdChoice"); }
		}

		///<summary>
		/// A Levels First Choice Label
		///</summary>
		[ImplementPropertyType("labelAlevelsFirstChoice")]
		public string LabelAlevelsFirstChoice
		{
			get { return this.GetPropertyValue<string>("labelAlevelsFirstChoice"); }
		}

		///<summary>
		/// A Levels Third Choice Label
		///</summary>
		[ImplementPropertyType("labelAlevelsThirdChoice")]
		public string LabelAlevelsThirdChoice
		{
			get { return this.GetPropertyValue<string>("labelAlevelsThirdChoice"); }
		}

		///<summary>
		/// Date Of Birth Label
		///</summary>
		[ImplementPropertyType("labelDateOfBirth")]
		public string LabelDateOfBirth
		{
			get { return this.GetPropertyValue<string>("labelDateOfBirth"); }
		}

		///<summary>
		/// Email Label
		///</summary>
		[ImplementPropertyType("labelEmail")]
		public string LabelEmail
		{
			get { return this.GetPropertyValue<string>("labelEmail"); }
		}

		///<summary>
		/// Ethnicity Label
		///</summary>
		[ImplementPropertyType("labelEthnicity")]
		public string LabelEthnicity
		{
			get { return this.GetPropertyValue<string>("labelEthnicity"); }
		}

		///<summary>
		/// First Language Label
		///</summary>
		[ImplementPropertyType("labelFirstLanguage")]
		public string LabelFirstLanguage
		{
			get { return this.GetPropertyValue<string>("labelFirstLanguage"); }
		}

		///<summary>
		/// First Name Label
		///</summary>
		[ImplementPropertyType("labelFirstName")]
		public string LabelFirstName
		{
			get { return this.GetPropertyValue<string>("labelFirstName"); }
		}

		///<summary>
		/// Gender Label
		///</summary>
		[ImplementPropertyType("labelGender")]
		public string LabelGender
		{
			get { return this.GetPropertyValue<string>("labelGender"); }
		}

		///<summary>
		/// Grade Label
		///</summary>
		[ImplementPropertyType("labelGrade")]
		public string LabelGrade
		{
			get { return this.GetPropertyValue<string>("labelGrade"); }
		}

		///<summary>
		/// Have Criminal Conviction Label
		///</summary>
		[ImplementPropertyType("labelHaveCriminalConviction")]
		public string LabelHaveCriminalConviction
		{
			get { return this.GetPropertyValue<string>("labelHaveCriminalConviction"); }
		}

		///<summary>
		/// Have Learning Disability/Difficulty Label
		///</summary>
		[ImplementPropertyType("labelHaveLearningDisabilityDifficulty")]
		public string LabelHaveLearningDisabilityDifficulty
		{
			get { return this.GetPropertyValue<string>("labelHaveLearningDisabilityDifficulty"); }
		}

		///<summary>
		/// Home Address Label
		///</summary>
		[ImplementPropertyType("labelHomeAddress")]
		public string LabelHomeAddress
		{
			get { return this.GetPropertyValue<string>("labelHomeAddress"); }
		}

		///<summary>
		/// Home Number Label
		///</summary>
		[ImplementPropertyType("labelHomeNumber")]
		public string LabelHomeNumber
		{
			get { return this.GetPropertyValue<string>("labelHomeNumber"); }
		}

		///<summary>
		/// Last Name Label
		///</summary>
		[ImplementPropertyType("labelLastName")]
		public string LabelLastName
		{
			get { return this.GetPropertyValue<string>("labelLastName"); }
		}

		///<summary>
		/// Middle Name Label
		///</summary>
		[ImplementPropertyType("labelMiddleName")]
		public string LabelMiddleName
		{
			get { return this.GetPropertyValue<string>("labelMiddleName"); }
		}

		///<summary>
		/// Mobile Number Label
		///</summary>
		[ImplementPropertyType("labelMobileNumber")]
		public string LabelMobileNumber
		{
			get { return this.GetPropertyValue<string>("labelMobileNumber"); }
		}

		///<summary>
		/// National Insurance Number Label
		///</summary>
		[ImplementPropertyType("labelNationalInsuranceNumber")]
		public string LabelNationalInsuranceNumber
		{
			get { return this.GetPropertyValue<string>("labelNationalInsuranceNumber"); }
		}

		///<summary>
		/// Nationality Label
		///</summary>
		[ImplementPropertyType("labelNationality")]
		public string LabelNationality
		{
			get { return this.GetPropertyValue<string>("labelNationality"); }
		}

		///<summary>
		/// No Criminal Conviction Label
		///</summary>
		[ImplementPropertyType("labelNoCriminalConviction")]
		public string LabelNoCriminalConviction
		{
			get { return this.GetPropertyValue<string>("labelNoCriminalConviction"); }
		}

		///<summary>
		/// No Learning Disability/Difficulty Label
		///</summary>
		[ImplementPropertyType("labelNoLearningDisabilityDifficulty")]
		public string LabelNoLearningDisabilityDifficulty
		{
			get { return this.GetPropertyValue<string>("labelNoLearningDisabilityDifficulty"); }
		}

		///<summary>
		/// Phone Number Label
		///</summary>
		[ImplementPropertyType("labelPhoneNumber")]
		public string LabelPhoneNumber
		{
			get { return this.GetPropertyValue<string>("labelPhoneNumber"); }
		}

		///<summary>
		/// Preferred Name Label
		///</summary>
		[ImplementPropertyType("labelPreferredName")]
		public string LabelPreferredName
		{
			get { return this.GetPropertyValue<string>("labelPreferredName"); }
		}

		///<summary>
		/// Primary Disability/Difficulty Label
		///</summary>
		[ImplementPropertyType("labelPrimaryDisabilityDifficulty")]
		public string LabelPrimaryDisabilityDifficulty
		{
			get { return this.GetPropertyValue<string>("labelPrimaryDisabilityDifficulty"); }
		}

		///<summary>
		/// Relationship To Student Label
		///</summary>
		[ImplementPropertyType("labelRelationshipToStudent")]
		public string LabelRelationshipToStudent
		{
			get { return this.GetPropertyValue<string>("labelRelationshipToStudent"); }
		}

		///<summary>
		/// Religion Label
		///</summary>
		[ImplementPropertyType("labelReligion")]
		public string LabelReligion
		{
			get { return this.GetPropertyValue<string>("labelReligion"); }
		}

		///<summary>
		/// Resident of UK/EU For 3 Years Label
		///</summary>
		[ImplementPropertyType("labelResidentOfUkEuFor3Years")]
		public string LabelResidentOfUkEuFor3Years
		{
			get { return this.GetPropertyValue<string>("labelResidentOfUkEuFor3Years"); }
		}

		///<summary>
		/// A Levels Second Choice Label
		///</summary>
		[ImplementPropertyType("labelsAlevelsSecondChoice")]
		public string LabelsAlevelsSecondChoice
		{
			get { return this.GetPropertyValue<string>("labelsAlevelsSecondChoice"); }
		}

		///<summary>
		/// Sports Academies Applying To Label
		///</summary>
		[ImplementPropertyType("labelSportsAcademiesApplyingTo")]
		public string LabelSportsAcademiesApplyingTo
		{
			get { return this.GetPropertyValue<string>("labelSportsAcademiesApplyingTo"); }
		}

		///<summary>
		/// Student's Email Label
		///</summary>
		[ImplementPropertyType("labelStudentsEmail")]
		public string LabelStudentsEmail
		{
			get { return this.GetPropertyValue<string>("labelStudentsEmail"); }
		}

		///<summary>
		/// Subject Label
		///</summary>
		[ImplementPropertyType("labelSubject")]
		public string LabelSubject
		{
			get { return this.GetPropertyValue<string>("labelSubject"); }
		}

		///<summary>
		/// Type Label
		///</summary>
		[ImplementPropertyType("labelType")]
		public string LabelType
		{
			get { return this.GetPropertyValue<string>("labelType"); }
		}

		///<summary>
		/// Year Label
		///</summary>
		[ImplementPropertyType("labelYear")]
		public string LabelYear
		{
			get { return this.GetPropertyValue<string>("labelYear"); }
		}

		///<summary>
		/// Course Selection Review Heading: This section will display information for courses(A-Levels) selected by the student
		///</summary>
		[ImplementPropertyType("reviewHeadingCourseSelection")]
		public string ReviewHeadingCourseSelection
		{
			get { return this.GetPropertyValue<string>("reviewHeadingCourseSelection"); }
		}

		///<summary>
		/// Criminal Convictions Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingCriminalConvictions")]
		public string ReviewHeadingCriminalConvictions
		{
			get { return this.GetPropertyValue<string>("reviewHeadingCriminalConvictions"); }
		}

		///<summary>
		/// Emergency Contact Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingEmergencyContact")]
		public string ReviewHeadingEmergencyContact
		{
			get { return this.GetPropertyValue<string>("reviewHeadingEmergencyContact"); }
		}

		///<summary>
		/// Equal Opportunities Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingEqualOpportunities")]
		public string ReviewHeadingEqualOpportunities
		{
			get { return this.GetPropertyValue<string>("reviewHeadingEqualOpportunities"); }
		}

		///<summary>
		/// Medical Conditions Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingMedicalConditions")]
		public string ReviewHeadingMedicalConditions
		{
			get { return this.GetPropertyValue<string>("reviewHeadingMedicalConditions"); }
		}

		///<summary>
		/// Parent/Carer Details Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingParentCarerDetails")]
		public string ReviewHeadingParentCarerDetails
		{
			get { return this.GetPropertyValue<string>("reviewHeadingParentCarerDetails"); }
		}

		///<summary>
		/// Previous Qualifications Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingPreviousQualifications")]
		public string ReviewHeadingPreviousQualifications
		{
			get { return this.GetPropertyValue<string>("reviewHeadingPreviousQualifications"); }
		}

		///<summary>
		/// Primary Contact Details Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingPrimaryContactDetails")]
		public string ReviewHeadingPrimaryContactDetails
		{
			get { return this.GetPropertyValue<string>("reviewHeadingPrimaryContactDetails"); }
		}

		///<summary>
		/// Sports Academies Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingSportsAcademies")]
		public string ReviewHeadingSportsAcademies
		{
			get { return this.GetPropertyValue<string>("reviewHeadingSportsAcademies"); }
		}

		///<summary>
		/// Student's Contact Information Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingStudentsContactInformation")]
		public string ReviewHeadingStudentsContactInformation
		{
			get { return this.GetPropertyValue<string>("reviewHeadingStudentsContactInformation"); }
		}

		///<summary>
		/// Student's Personal Information Review Heading
		///</summary>
		[ImplementPropertyType("reviewHeadingStudentsPersonalInformation")]
		public string ReviewHeadingStudentsPersonalInformation
		{
			get { return this.GetPropertyValue<string>("reviewHeadingStudentsPersonalInformation"); }
		}

		///<summary>
		/// You Are Applying For Review Heading: This section will display information for the course if it wasn't A-Levels
		///</summary>
		[ImplementPropertyType("reviewHeadingYouAreApplyingFor")]
		public string ReviewHeadingYouAreApplyingFor
		{
			get { return this.GetPropertyValue<string>("reviewHeadingYouAreApplyingFor"); }
		}

		///<summary>
		/// Sub Heading
		///</summary>
		[ImplementPropertyType("subHeading")]
		public string SubHeading
		{
			get { return this.GetPropertyValue<string>("subHeading"); }
		}

		///<summary>
		/// Continue Button Text
		///</summary>
		[ImplementPropertyType("textContinueButton")]
		public string TextContinueButton
		{
			get { return this.GetPropertyValue<string>("textContinueButton"); }
		}

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("heading")]
		public string Heading
		{
			get { return USP.Business.Models.ContentModels.BaseHeading.GetHeading(this); }
		}

		///<summary>
		/// Hide From Sitemap
		///</summary>
		[ImplementPropertyType("hideFromSitemap")]
		public bool HideFromSitemap
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetHideFromSitemap(this); }
		}

		///<summary>
		/// Metadata Description
		///</summary>
		[ImplementPropertyType("metadataDescription")]
		public string MetadataDescription
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataDescription(this); }
		}

		///<summary>
		/// Metadata Keywords
		///</summary>
		[ImplementPropertyType("metadataKeywords")]
		public IEnumerable<string> MetadataKeywords
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataKeywords(this); }
		}

		///<summary>
		/// Metadata Title
		///</summary>
		[ImplementPropertyType("metadataTitle")]
		public string MetadataTitle
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataTitle(this); }
		}

		///<summary>
		/// Hide Children From Navigation: Hides all child pages from navigation menus
		///</summary>
		[ImplementPropertyType("hideChildrenFromNavigation")]
		public bool HideChildrenFromNavigation
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideChildrenFromNavigation(this); }
		}

		///<summary>
		/// Hide From Navigation: Hides both this page and it's children from navigation menus
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideFromNavigation(this); }
		}

		///<summary>
		/// Hide From Search: Do not show this page in search result or listing pages
		///</summary>
		[ImplementPropertyType("hideFromSearch")]
		public bool HideFromSearch
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideFromSearch(this); }
		}

		///<summary>
		/// Navigation Title: Name of page shown in breadcrumb and navigation menus
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetNavigationTitle(this); }
		}
	}
}
