//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Page] Home</summary>
	[PublishedContentModel("pageHome")]
	public partial class PageHome : PublishedContentModel, IBaseMetaInformation, IBaseNavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageHome";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageHome(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageHome, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// All Courses Button Label
		///</summary>
		[ImplementPropertyType("allCoursesButtonLabel")]
		public string AllCoursesButtonLabel
		{
			get { return this.GetPropertyValue<string>("allCoursesButtonLabel"); }
		}

		///<summary>
		/// All Courses Short Copy
		///</summary>
		[ImplementPropertyType("allCoursesShortCopy")]
		public string AllCoursesShortCopy
		{
			get { return this.GetPropertyValue<string>("allCoursesShortCopy"); }
		}

		///<summary>
		/// Call To Action
		///</summary>
		[ImplementPropertyType("callToAction")]
		public Umbraco.Web.Models.RelatedLinks CallToAction
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("callToAction"); }
		}

		///<summary>
		/// Childcare Sector Label
		///</summary>
		[ImplementPropertyType("childcareSectorLabel")]
		public string ChildcareSectorLabel
		{
			get { return this.GetPropertyValue<string>("childcareSectorLabel"); }
		}

		///<summary>
		/// Childcare Sector Link
		///</summary>
		[ImplementPropertyType("childcareSectorLink")]
		public IEnumerable<IPublishedContent> ChildcareSectorLink
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("childcareSectorLink"); }
		}

		///<summary>
		/// Course Career Search Page
		///</summary>
		[ImplementPropertyType("courseCareerSearchPage")]
		public IEnumerable<IPublishedContent> CourseCareerSearchPage
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("courseCareerSearchPage"); }
		}

		///<summary>
		/// All courses Link: Link to an unfiltered course listing page
		///</summary>
		[ImplementPropertyType("courseListingLink")]
		public IEnumerable<IPublishedContent> CourseListingLink
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("courseListingLink"); }
		}

		///<summary>
		/// Creative Digital Sector Label
		///</summary>
		[ImplementPropertyType("creativeAndDigitalLabel")]
		public string CreativeAndDigitalLabel
		{
			get { return this.GetPropertyValue<string>("creativeAndDigitalLabel"); }
		}

		///<summary>
		/// Creative Digital Sector Link
		///</summary>
		[ImplementPropertyType("creativeAndDigitalLink")]
		public IEnumerable<IPublishedContent> CreativeAndDigitalLink
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("creativeAndDigitalLink"); }
		}

		///<summary>
		/// Financial Sector Label
		///</summary>
		[ImplementPropertyType("financialSectorLabel")]
		public string FinancialSectorLabel
		{
			get { return this.GetPropertyValue<string>("financialSectorLabel"); }
		}

		///<summary>
		/// Financial Sector Link
		///</summary>
		[ImplementPropertyType("financialSectorLink")]
		public IEnumerable<IPublishedContent> FinancialSectorLink
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("financialSectorLink"); }
		}

		///<summary>
		/// Healthcare Sector Label
		///</summary>
		[ImplementPropertyType("healthcareAndMedicalLabel")]
		public string HealthcareAndMedicalLabel
		{
			get { return this.GetPropertyValue<string>("healthcareAndMedicalLabel"); }
		}

		///<summary>
		/// Healthcare Sector Link
		///</summary>
		[ImplementPropertyType("healthcareAndMedicalLink")]
		public IEnumerable<IPublishedContent> HealthcareAndMedicalLink
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("healthcareAndMedicalLink"); }
		}

		///<summary>
		/// Home Widgets
		///</summary>
		[ImplementPropertyType("homeWidgets")]
		public Newtonsoft.Json.Linq.JToken HomeWidgets
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("homeWidgets"); }
		}

		///<summary>
		/// Search Button Label
		///</summary>
		[ImplementPropertyType("searchButtonLabel")]
		public string SearchButtonLabel
		{
			get { return this.GetPropertyValue<string>("searchButtonLabel"); }
		}

		///<summary>
		/// Search Hint Text
		///</summary>
		[ImplementPropertyType("searchHintText")]
		public string SearchHintText
		{
			get { return this.GetPropertyValue<string>("searchHintText"); }
		}

		///<summary>
		/// Search Title
		///</summary>
		[ImplementPropertyType("searchTitle")]
		public string SearchTitle
		{
			get { return this.GetPropertyValue<string>("searchTitle"); }
		}

		///<summary>
		/// Short Copy
		///</summary>
		[ImplementPropertyType("shortCopy")]
		public IHtmlString ShortCopy
		{
			get { return this.GetPropertyValue<IHtmlString>("shortCopy"); }
		}

		///<summary>
		/// Show Alert
		///</summary>
		[ImplementPropertyType("showAlert")]
		public bool ShowAlert
		{
			get { return this.GetPropertyValue<bool>("showAlert"); }
		}

		///<summary>
		/// Sport Science Label
		///</summary>
		[ImplementPropertyType("sportScienceLabel")]
		public string SportScienceLabel
		{
			get { return this.GetPropertyValue<string>("sportScienceLabel"); }
		}

		///<summary>
		/// Sport Science Link
		///</summary>
		[ImplementPropertyType("sportScienceLink")]
		public IEnumerable<IPublishedContent> SportScienceLink
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sportScienceLink"); }
		}

		///<summary>
		/// Alert Text
		///</summary>
		[ImplementPropertyType("textAlert")]
		public string TextAlert
		{
			get { return this.GetPropertyValue<string>("textAlert"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Hide From Sitemap
		///</summary>
		[ImplementPropertyType("hideFromSitemap")]
		public bool HideFromSitemap
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetHideFromSitemap(this); }
		}

		///<summary>
		/// Metadata Description
		///</summary>
		[ImplementPropertyType("metadataDescription")]
		public string MetadataDescription
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataDescription(this); }
		}

		///<summary>
		/// Metadata Keywords
		///</summary>
		[ImplementPropertyType("metadataKeywords")]
		public IEnumerable<string> MetadataKeywords
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataKeywords(this); }
		}

		///<summary>
		/// Metadata Title
		///</summary>
		[ImplementPropertyType("metadataTitle")]
		public string MetadataTitle
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataTitle(this); }
		}

		///<summary>
		/// Hide Children From Navigation: Hides all child pages from navigation menus
		///</summary>
		[ImplementPropertyType("hideChildrenFromNavigation")]
		public bool HideChildrenFromNavigation
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideChildrenFromNavigation(this); }
		}

		///<summary>
		/// Hide From Navigation: Hides both this page and it's children from navigation menus
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideFromNavigation(this); }
		}

		///<summary>
		/// Hide From Search: Do not show this page in search result or listing pages
		///</summary>
		[ImplementPropertyType("hideFromSearch")]
		public bool HideFromSearch
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideFromSearch(this); }
		}

		///<summary>
		/// Navigation Title: Name of page shown in breadcrumb and navigation menus
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetNavigationTitle(this); }
		}
	}
}
