//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Page] Account Creation</summary>
	[PublishedContentModel("pageRegistration")]
	public partial class PageRegistration : PublishedContentModel, IBaseArticleGrid, IBaseHeading, IBaseMetaInformation, IBaseNavigation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageRegistration";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageRegistration(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageRegistration, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body: Account created confirmation email body
		///</summary>
		[ImplementPropertyType("emailBody")]
		public IHtmlString EmailBody
		{
			get { return this.GetPropertyValue<IHtmlString>("emailBody"); }
		}

		///<summary>
		/// From
		///</summary>
		[ImplementPropertyType("emailFrom")]
		public string EmailFrom
		{
			get { return this.GetPropertyValue<string>("emailFrom"); }
		}

		///<summary>
		/// Subject
		///</summary>
		[ImplementPropertyType("emailSubject")]
		public string EmailSubject
		{
			get { return this.GetPropertyValue<string>("emailSubject"); }
		}

		///<summary>
		/// Account Creation Reason Text
		///</summary>
		[ImplementPropertyType("information")]
		public string Information
		{
			get { return this.GetPropertyValue<string>("information"); }
		}

		///<summary>
		/// Accept Terms And Conditions Label
		///</summary>
		[ImplementPropertyType("labelAcceptTermsAndConditions")]
		public string LabelAcceptTermsAndConditions
		{
			get { return this.GetPropertyValue<string>("labelAcceptTermsAndConditions"); }
		}

		///<summary>
		/// Email Label
		///</summary>
		[ImplementPropertyType("labelEmail")]
		public string LabelEmail
		{
			get { return this.GetPropertyValue<string>("labelEmail"); }
		}

		///<summary>
		/// Password Label
		///</summary>
		[ImplementPropertyType("labelPassword")]
		public string LabelPassword
		{
			get { return this.GetPropertyValue<string>("labelPassword"); }
		}

		///<summary>
		/// Repeat Password Label
		///</summary>
		[ImplementPropertyType("labelRepeatPassword")]
		public string LabelRepeatPassword
		{
			get { return this.GetPropertyValue<string>("labelRepeatPassword"); }
		}

		///<summary>
		/// Login Page
		///</summary>
		[ImplementPropertyType("loginPage")]
		public IEnumerable<IPublishedContent> LoginPage
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("loginPage"); }
		}

		///<summary>
		/// Login Page Link Text
		///</summary>
		[ImplementPropertyType("loginPageLinkText")]
		public string LoginPageLinkText
		{
			get { return this.GetPropertyValue<string>("loginPageLinkText"); }
		}

		///<summary>
		/// Password Requirement Alert Heading
		///</summary>
		[ImplementPropertyType("passwordRequirementAlertHeading")]
		public string PasswordRequirementAlertHeading
		{
			get { return this.GetPropertyValue<string>("passwordRequirementAlertHeading"); }
		}

		///<summary>
		/// Password Requirement List Items
		///</summary>
		[ImplementPropertyType("passwordRequirementListItems")]
		public IEnumerable<string> PasswordRequirementListItems
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("passwordRequirementListItems"); }
		}

		///<summary>
		/// Terms And Conditions - Rich Text
		///</summary>
		[ImplementPropertyType("richTextTermsAndConditions")]
		public IHtmlString RichTextTermsAndConditions
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextTermsAndConditions"); }
		}

		///<summary>
		/// Already A Member Header
		///</summary>
		[ImplementPropertyType("subHeading")]
		public string SubHeading
		{
			get { return this.GetPropertyValue<string>("subHeading"); }
		}

		///<summary>
		/// Create Account Button Text
		///</summary>
		[ImplementPropertyType("textCreateAccountButton")]
		public string TextCreateAccountButton
		{
			get { return this.GetPropertyValue<string>("textCreateAccountButton"); }
		}

		///<summary>
		/// Greeting Text
		///</summary>
		[ImplementPropertyType("textGreeting")]
		public string TextGreeting
		{
			get { return this.GetPropertyValue<string>("textGreeting"); }
		}

		///<summary>
		/// Main Content Placeholder
		///</summary>
		[ImplementPropertyType("mainContentPlaceholder")]
		public Newtonsoft.Json.Linq.JToken MainContentPlaceholder
		{
			get { return USP.Business.Models.ContentModels.BaseArticleGrid.GetMainContentPlaceholder(this); }
		}

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("heading")]
		public string Heading
		{
			get { return USP.Business.Models.ContentModels.BaseHeading.GetHeading(this); }
		}

		///<summary>
		/// Hide From Sitemap
		///</summary>
		[ImplementPropertyType("hideFromSitemap")]
		public bool HideFromSitemap
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetHideFromSitemap(this); }
		}

		///<summary>
		/// Metadata Description
		///</summary>
		[ImplementPropertyType("metadataDescription")]
		public string MetadataDescription
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataDescription(this); }
		}

		///<summary>
		/// Metadata Keywords
		///</summary>
		[ImplementPropertyType("metadataKeywords")]
		public IEnumerable<string> MetadataKeywords
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataKeywords(this); }
		}

		///<summary>
		/// Metadata Title
		///</summary>
		[ImplementPropertyType("metadataTitle")]
		public string MetadataTitle
		{
			get { return USP.Business.Models.ContentModels.BaseMetaInformation.GetMetadataTitle(this); }
		}

		///<summary>
		/// Hide Children From Navigation: Hides all child pages from navigation menus
		///</summary>
		[ImplementPropertyType("hideChildrenFromNavigation")]
		public bool HideChildrenFromNavigation
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideChildrenFromNavigation(this); }
		}

		///<summary>
		/// Hide From Navigation: Hides both this page and it's children from navigation menus
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideFromNavigation(this); }
		}

		///<summary>
		/// Hide From Search: Do not show this page in search result or listing pages
		///</summary>
		[ImplementPropertyType("hideFromSearch")]
		public bool HideFromSearch
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetHideFromSearch(this); }
		}

		///<summary>
		/// Navigation Title: Name of page shown in breadcrumb and navigation menus
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return USP.Business.Models.ContentModels.BaseNavigation.GetNavigationTitle(this); }
		}
	}
}
