//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Settings] Twitter</summary>
	[PublishedContentModel("settingsTwitter")]
	public partial class SettingsTwitter : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settingsTwitter";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SettingsTwitter(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SettingsTwitter, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Access Token
		///</summary>
		[ImplementPropertyType("accessToken")]
		public string AccessToken
		{
			get { return this.GetPropertyValue<string>("accessToken"); }
		}

		///<summary>
		/// Account Username: Twitter handle, without the @
		///</summary>
		[ImplementPropertyType("accountUsername")]
		public string AccountUsername
		{
			get { return this.GetPropertyValue<string>("accountUsername"); }
		}

		///<summary>
		/// Consumer Key
		///</summary>
		[ImplementPropertyType("consumerKey")]
		public string ConsumerKey
		{
			get { return this.GetPropertyValue<string>("consumerKey"); }
		}

		///<summary>
		/// Consumer Secret
		///</summary>
		[ImplementPropertyType("consumerSecret")]
		public string ConsumerSecret
		{
			get { return this.GetPropertyValue<string>("consumerSecret"); }
		}

		///<summary>
		/// No Of Posts: Number of tweets to show
		///</summary>
		[ImplementPropertyType("noOfPosts")]
		public int NoOfPosts
		{
			get { return this.GetPropertyValue<int>("noOfPosts"); }
		}

		///<summary>
		/// Token Secret
		///</summary>
		[ImplementPropertyType("tokenSecret")]
		public string TokenSecret
		{
			get { return this.GetPropertyValue<string>("tokenSecret"); }
		}
	}
}
