//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	// Mixin content Type 1196 with alias "settingsCookieMessage"
	/// <summary>[Settings] Cookie Message</summary>
	public partial interface ISettingsCookieMessage : IPublishedContent
	{
		/// <summary>Cookie Accept Text</summary>
		string CookieAcceptText { get; }

		/// <summary>Cookie Message</summary>
		IHtmlString CookieMessage { get; }

		/// <summary>Essential Cookie Text</summary>
		string EssentialCookieText { get; }

		/// <summary>Other Cookie Text</summary>
		string OtherCookieText { get; }
	}

	/// <summary>[Settings] Cookie Message</summary>
	[PublishedContentModel("settingsCookieMessage")]
	public partial class SettingsCookieMessage : PublishedContentModel, ISettingsCookieMessage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settingsCookieMessage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SettingsCookieMessage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SettingsCookieMessage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cookie Accept Text: Text for cookie accept button
		///</summary>
		[ImplementPropertyType("cookieAcceptText")]
		public string CookieAcceptText
		{
			get { return GetCookieAcceptText(this); }
		}

		/// <summary>Static getter for Cookie Accept Text</summary>
		public static string GetCookieAcceptText(ISettingsCookieMessage that) { return that.GetPropertyValue<string>("cookieAcceptText"); }

		///<summary>
		/// Cookie Message
		///</summary>
		[ImplementPropertyType("cookieMessage")]
		public IHtmlString CookieMessage
		{
			get { return GetCookieMessage(this); }
		}

		/// <summary>Static getter for Cookie Message</summary>
		public static IHtmlString GetCookieMessage(ISettingsCookieMessage that) { return that.GetPropertyValue<IHtmlString>("cookieMessage"); }

		///<summary>
		/// Essential Cookie Text
		///</summary>
		[ImplementPropertyType("essentialCookieText")]
		public string EssentialCookieText
		{
			get { return GetEssentialCookieText(this); }
		}

		/// <summary>Static getter for Essential Cookie Text</summary>
		public static string GetEssentialCookieText(ISettingsCookieMessage that) { return that.GetPropertyValue<string>("essentialCookieText"); }

		///<summary>
		/// Other Cookie Text
		///</summary>
		[ImplementPropertyType("otherCookieText")]
		public string OtherCookieText
		{
			get { return GetOtherCookieText(this); }
		}

		/// <summary>Static getter for Other Cookie Text</summary>
		public static string GetOtherCookieText(ISettingsCookieMessage that) { return that.GetPropertyValue<string>("otherCookieText"); }
	}
}
