//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Settings] Site</summary>
	[PublishedContentModel("settingsSite")]
	public partial class SettingsSite : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settingsSite";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SettingsSite(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SettingsSite, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Analytics Script
		///</summary>
		[ImplementPropertyType("analyticsScript")]
		public string AnalyticsScript
		{
			get { return this.GetPropertyValue<string>("analyticsScript"); }
		}

		///<summary>
		/// Campus List
		///</summary>
		[ImplementPropertyType("campusList")]
		public IEnumerable<IPublishedContent> CampusList
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("campusList"); }
		}

		///<summary>
		/// Copyright Text
		///</summary>
		[ImplementPropertyType("copyrightText")]
		public string CopyrightText
		{
			get { return this.GetPropertyValue<string>("copyrightText"); }
		}

		///<summary>
		/// Facebook Link: Link to company Facebook page
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return this.GetPropertyValue<string>("facebookLink"); }
		}

		///<summary>
		/// File Type Descriptions
		///</summary>
		[ImplementPropertyType("fileTypeDescriptions")]
		public IEnumerable<IPublishedContent> FileTypeDescriptions
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("fileTypeDescriptions"); }
		}

		///<summary>
		/// Footer Links: Main links for the footer
		///</summary>
		[ImplementPropertyType("footerLinks")]
		public Umbraco.Web.Models.RelatedLinks FooterLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("footerLinks"); }
		}

		///<summary>
		/// LinkedIn Link: Link to company LinkedIn page
		///</summary>
		[ImplementPropertyType("linkedInLink")]
		public string LinkedInLink
		{
			get { return this.GetPropertyValue<string>("linkedInLink"); }
		}

		///<summary>
		/// Logo List
		///</summary>
		[ImplementPropertyType("logoList")]
		public IEnumerable<IPublishedContent> LogoList
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("logoList"); }
		}

		///<summary>
		/// Main Event Listing Page: Main event Listing page is the event listing page where 'Only Show Children' is set to false
		///</summary>
		[ImplementPropertyType("mainEventListingPage")]
		public IEnumerable<IPublishedContent> MainEventListingPage
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("mainEventListingPage"); }
		}

		///<summary>
		/// Main Event Listing Page CTA Text
		///</summary>
		[ImplementPropertyType("mainEventListingPageCtaText")]
		public string MainEventListingPageCtaText
		{
			get { return this.GetPropertyValue<string>("mainEventListingPageCtaText"); }
		}

		///<summary>
		/// Policy Links: Links to terms and conditions, FAQs, privacy policy, etc.
		///</summary>
		[ImplementPropertyType("policyLinks")]
		public Umbraco.Web.Models.RelatedLinks PolicyLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("policyLinks"); }
		}

		///<summary>
		/// Search Page
		///</summary>
		[ImplementPropertyType("searchPage")]
		public IEnumerable<IPublishedContent> SearchPage
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("searchPage"); }
		}

		///<summary>
		/// Signin Links
		///</summary>
		[ImplementPropertyType("signinLinks")]
		public Umbraco.Web.Models.RelatedLinks SigninLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("signinLinks"); }
		}

		///<summary>
		/// Twitter Link: Link to company Twitter page
		///</summary>
		[ImplementPropertyType("twitterLink")]
		public string TwitterLink
		{
			get { return this.GetPropertyValue<string>("twitterLink"); }
		}

		///<summary>
		/// Utility Links
		///</summary>
		[ImplementPropertyType("utilityLinks")]
		public Umbraco.Web.Models.RelatedLinks UtilityLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("utilityLinks"); }
		}

		///<summary>
		/// YouTube Link: Link to company YouTube page
		///</summary>
		[ImplementPropertyType("youTubeLink")]
		public string YouTubeLink
		{
			get { return this.GetPropertyValue<string>("youTubeLink"); }
		}
	}
}
