//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Widget] Carousel Spotlight</summary>
	[PublishedContentModel("widgetCarouselSpotlight")]
	public partial class WidgetCarouselSpotlight : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "widgetCarouselSpotlight";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public WidgetCarouselSpotlight(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WidgetCarouselSpotlight, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Left Spotlight Items
		///</summary>
		[ImplementPropertyType("leftSpotlightItems")]
		public IEnumerable<IPublishedContent> LeftSpotlightItems
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("leftSpotlightItems"); }
		}

		///<summary>
		/// Left Spotlight Title
		///</summary>
		[ImplementPropertyType("leftSpotlightTitle")]
		public string LeftSpotlightTitle
		{
			get { return this.GetPropertyValue<string>("leftSpotlightTitle"); }
		}

		///<summary>
		/// Right Spotlight Items
		///</summary>
		[ImplementPropertyType("rightSpotlightItems")]
		public IEnumerable<IPublishedContent> RightSpotlightItems
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("rightSpotlightItems"); }
		}

		///<summary>
		/// Right Spotlight Title
		///</summary>
		[ImplementPropertyType("rightSpotlightTitle")]
		public string RightSpotlightTitle
		{
			get { return this.GetPropertyValue<string>("rightSpotlightTitle"); }
		}
	}
}
