//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace USP.Business.Models.ContentModels
{
	/// <summary>[Widget] Video</summary>
	[PublishedContentModel("widgetVideo")]
	public partial class WidgetVideo : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "widgetVideo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public WidgetVideo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WidgetVideo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cover Image: Cover image
		///</summary>
		[ImplementPropertyType("coverImage")]
		public IPublishedContent CoverImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("coverImage"); }
		}

		///<summary>
		/// Overlay: Overlay colour for image
		///</summary>
		[ImplementPropertyType("overlay")]
		public object Overlay
		{
			get { return this.GetPropertyValue("overlay"); }
		}

		///<summary>
		/// YouTube ID
		///</summary>
		[ImplementPropertyType("youTubeID")]
		public string YouTubeID
		{
			get { return this.GetPropertyValue<string>("youTubeID"); }
		}
        [ImplementPropertyType("title")]
        public string VideoTitle
        {
            get { return this.GetPropertyValue<string>("title"); }
        }
    }
}
