USE [USP-Application-Form]
GO

/****** Object:  StoredProcedure [dbo].[GetApplication]    Script Date: 13/09/2018 16:29:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[GetApplication] 
	@UserId uniqueidentifier
AS
	SELECT [ID]
		  ,[UserId]
		  ,[IsSubmitted]
		  ,[DateSubmitted]
		  ,[TypeOfStudy]
		  ,[Campus]
		  ,[IsStepTwoSubmitted]
		  ,[IsStepThreeSubmitted]
		  ,[IsStepFourSubmitted] 
		  ,[IsStepFiveSubmitted] 
		  ,[IsStepSixSubmitted] 
		  ,[IsStepSevenSubmitted] 
		  ,[IsStepEightSubmitted] 
		  ,[IsStepNineSubmitted]
		  ,[IsStepTenSubmitted] 
	      ,[IsStepElevenSubmitted] 
		  ,[IsStepTwelveSubmitted] 
		  ,[StudentsFirstName] 
		  ,[StudentsMiddleName] 
		  ,[StudentsLastName] 
		  ,[StudentsPreferedName] 
		  ,[StudentsDateOfBirth] 
		  ,[StudentsGender] 
		  ,[StudentsHomeAddressLine1] 
		  ,[StudentsHomeAddressLine2] 
		  ,[StudentsHomePostCode] 
		  ,[StudentsTownOrCity] 
		  ,[StudentsMobileNumber] 
		  ,[StudentsHomeNumber] 
		  ,[StudentsEmailAddress] 
		  ,[EmergencyContactFirstName] 
		  ,[EmergencyContactLastName] 
		  ,[EmergencyContactRelationship] 
		  ,[EmergencyContactPhoneNumber]
		  ,[EmergencyContactEmailAddress] 
		  ,[ParentOrCarerFirstName] 
		  ,[ParentOrCarerLastName] 
	      ,[ParentOrCarerRelationshipToStudent]
		  ,[ParentOrCarerPhoneNumber] 
		  ,[ParentOrCarerEmailAddress] 
		  ,[IsParentOrCarerPrimaryContact]
		  ,[PrimaryContactFirstName] 
		  ,[PrimaryContactLastName] 
		  ,[PrimaryContactRelationshipToStudent] 
		  ,[PrimaryContactPhoneNumber] 
		  ,[PrimaryContactEmailAddress] 
		  ,[AlevelCourseFirstChoice]
		  ,[AlevelCourseSecondChoice] 
		  ,[AlevelCourseThirdChoice] 
		  ,[IsFirstFullLevel3Qualification] 
		  ,[NameOfCourseOfTheTypeSelected]
		  ,[SportsAcademiesCsv] 
		  ,[NameOfLastCollegeOrSchool] 
		  ,[QualificationsJson] 
		  ,[HasDisabilityDifficulty]
		  ,[DisabilitiesDifficultiesCsv] 
		  ,[PrimaryDisability] 
		  ,[StudentsEthnicity] 
		  ,[StudentsNationality] 
	      ,[StudentsReligion] 
		  ,[StudentsFirstLanguage] 
	      ,[ResidentOfUkEuForThreeYears] 
		  ,[NameOfCountryOutsideUkEu] 
		  ,[DateOfResidenceOutsideUkEuFrom]
		  ,[DateOfResidenceOutsideUkEuTo] 
		  ,[AnyCriminalConvictionOrFinalWarning]
		  ,[ReceiveMarketingEmails] 
		  ,[HowDidYouHearAboutThisCourse]
		  ,[MostInterestedSector]
		  ,[IsALevels]
		  ,[IsAdultLearning]
		  ,[IsApprenticeships] 
		  ,[IsProfessionalQualifications]
	  FROM [dbo].[Applications]
	  WHERE UserId = @UserId
GO

